using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Forms;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

using ClashSolver.UI.Controllers;
using ClashSolver.UI.Models;
using ClashSolver.UI.UIComponents;
using ContextMenu = System.Windows.Controls.ContextMenu;
using MenuItem = System.Windows.Controls.MenuItem;

namespace ClashSolver.UI.ValidationResolution.ReviewIssues
{
	/// <summary>
	/// Interaction logic for WndReviewIssues.xaml
	/// </summary>
	public partial class WndReviewIssues : Window, IExternal
	{
		private readonly ReviewIssuesUIController _formController = new ReviewIssuesUIController();
		private bool _isDisposed = false;

		private System.Windows.Controls.MenuItem menuItem;
		private ContextMenu cxMenu = null;

		public WndReviewIssues(ReviewIssuesUIController controller)
		{
			InitializeComponent();

			_formController = controller;
			DataContext = _formController;

			cmbStatus.ItemsSource = Enum.GetValues(typeof(IssueStatus));

			cmbVisibility.ItemsSource = Enum.GetValues(typeof(Visibility));

			WakeUp();

			Closed += OnClosed;
		}

		#region IExternal interface implementation
		private void OnClosed(object sender, EventArgs e)
		{
			_isDisposed = true;
		}

		public int GetRequestId()
		{
			return _formController.GetRequestId();
		}

		public void MakeRequest(int request)
		{
			_formController.MakeRequest(request);

			DozeOff();
		}

		public void DozeOff()
		{

		}

		public void WakeUp(bool bFinish = false)
		{
			if (bFinish)
			{
				Close();
				return;
			}

			_formController.WakeUp(bFinish);
		}

		public void IClose()
		{
			if (!_isDisposed)
			{
				Close();
				_isDisposed = true;
			}
		}

		public bool IVisible()
		{
			return Visibility == System.Windows.Visibility.Visible;
		}

		public bool IIsDisposed()
		{
			return _isDisposed;
		}

		public void IShow()
		{
			if (!_isDisposed)
			{
				Show();
			}
		}
		#endregion

		#region Event Handler

		private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
		{
			cxMenu = new ContextMenu();

			foreach(DataGridColumn item in gridIssues.Columns)
			{
				menuItem = new MenuItem();
				menuItem.Header = item.Header;
				menuItem.IsChecked = true;
				cxMenu.Items.Add(menuItem);
				menuItem.Click += new RoutedEventHandler(menuItem_Click);
			}
		}

		private void menuItem_Click(object sender, RoutedEventArgs e)
		{
			MenuItem item = sender as MenuItem;
			if (item.IsChecked)
			{
				item.IsChecked = false;
			}
			else
			{
				item.IsChecked = true;
			}
		}

		private void menuitem_Unchecked(object sender, RoutedEventArgs e)
		{
			MenuItem item = sender as MenuItem;
			foreach (DataGridColumn column in gridIssues.Columns)
			{
				// 
				if (column.Header.ToString().Contains(item.Header.ToString()))
				{
					gridIssues.Columns.Remove(column);
				}
			}
		}

		private void menuItem_Checked(object sender, RoutedEventArgs e)
		{
			MenuItem item = sender as MenuItem;
			gridIssues.AutoGeneratedColumns -= new EventHandler(DataGrid_AutoGeneratedColumns);
			List<string> menuList = new List<string>();
			menuList.Clear();

			foreach(MenuItem menuItem in cxMenu.Items)
			{
				if(menuItem.IsChecked == false)
				{
					menuList.Add(menuItem.Header.ToString());
				}
			}

			gridIssues.ItemsSource = null;

			foreach(string menuItem in menuList)
			{
				foreach (DataGridColumn column in gridIssues.Columns)
				{
					if (column.Header.ToString() == menuItem)
					{
						gridIssues.Columns.Remove(column);
					}
				}
			}

		}

		private void DataGrid_MouseRightButtonUp(object sender, MouseButtonEventArgs e)
		{
			DependencyObject depObj = (DependencyObject)e.OriginalSource;

		}
			

		private void btnSelAll_Click(object sender, RoutedEventArgs e)
		{
			gridIssues.SelectAll();
		}

		private void btnSelNone_Click(object sender, RoutedEventArgs e)
		{
			gridIssues.SelectedItems.Clear();
		}

		private void btnSelInvert_Click(object sender, RoutedEventArgs e)
		{
			// Get a copy of the currently IsSelected items
			var selectedItems = new List<object>((IEnumerable<object>)gridIssues.SelectedItems);

			// Clear the current selection
			gridIssues.UnselectAll();

			// Iterate through all items in the DataGrid
			foreach (var item in gridIssues.Items)
			{
				// Toggle the selection state
				if (!selectedItems.Contains(item))
				{
					gridIssues.SelectedItems.Add(item); // Select previously unselected items
				}
				else
				{
					gridIssues.SelectedItems.Remove(item); // Unselect previously IsSelected items
				}
			}
		}

		private void cmbStatus_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			int nIndex = cmbStatus.SelectedIndex;
			IssueStatus status = (IssueStatus)nIndex;

			_formController.FilterByStatus(status);
		}

		private void gridIssues_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{

		}

		private void gridIssues_MouseDoubleClick(object sender, MouseButtonEventArgs e)
		{
			var issue = gridIssues.SelectedItem as Issue;

			if (issue != null)
			{
				_formController.HighlightClash(issue);
			}
		}

		private async void btnAIResolve_Click(object sender, RoutedEventArgs e)
		{
			//var button = (System.Windows.Controls.Button)sender;
			//if (button != null)
			//{
			//	button.Content = "Waiting...";
			//}

			bool res = false;

			var issue = gridIssues.SelectedItem as Issue;

			if (issue != null)
			{
				issue.ResolveStatus = "Waiting...";
				res = await _formController.ResolveIssueAsync(issue);
				issue.ResolveStatus = "Done";
			}

			//if(button != null)
			//{
			//	button.Content = res? "Done":"Abort";
			//}
		}

		private void btnPrevious_Click(object sender, RoutedEventArgs e)
		{
			int temp = _formController.CurrentPageNumber;
			if (temp > 1)
				_formController.CurrentPageNumber = temp - 1;
		}

		private void btnNext_Click(object sender, RoutedEventArgs e)
		{
			int temp = _formController.CurrentPageNumber;
			if (temp < _formController.PageCount)
				_formController.CurrentPageNumber = temp + 1;
		}

		#endregion

		private void ShowHideColumns_Click(object sender, RoutedEventArgs e)
		{
			var dialog = new WindowColumnVisibility(gridIssues.Columns);
			dialog.Owner = Window.GetWindow(this);
			dialog.ShowDialog();
		}
    }
}
